const { contextBridge, ipcRenderer, webUtils } = require('electron');
const appVersion = ipcRenderer.sendSync('app:getVersion');
const isPackaged = ipcRenderer.sendSync('app:isPackaged');
const buildConfig = ipcRenderer.sendSync('config:get') || {};

contextBridge.exposeInMainWorld('winControls', {
  appVersion,
  isPackaged,
  buildConfig,
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  onMaximizedChange: (cb) => ipcRenderer.on('win:maximized', (e, isMax) => cb(isMax)),
  setAlwaysOnTop: (flag) => ipcRenderer.send('win:setAlwaysOnTop', flag),
  setResizable: (flag) => ipcRenderer.send('win:setResizable', flag),
  setDisplayMode: (mode) => ipcRenderer.send('win:setDisplayMode', mode),
  exportRecording: (buffer, suggestedName, duration, fps, quality) => ipcRenderer.invoke('rec:export', { buffer, suggestedName, duration, fps, quality }),
  onExportProgress: (cb) => ipcRenderer.on('rec:progress', (e, percent) => cb(percent)),
  onMediaPlayPause: (cb) => ipcRenderer.on('media:playpause', () => cb()),
  onMediaNext: (cb) => ipcRenderer.on('media:next', () => cb()),
  onMediaPrev: (cb) => ipcRenderer.on('media:prev', () => cb()),
  onOpenFile: (cb) => ipcRenderer.on('open-file', (e, payload) => cb(payload)),
  setMiniMode: (flag) => ipcRenderer.send('win:setMiniMode', flag),
  shakeWindow: (intensity) => ipcRenderer.send('win:shake', intensity),
  onFadeOut: (cb) => ipcRenderer.on('app:fadeout', () => cb()),
  thumbarInit: (icons) => ipcRenderer.invoke('thumbar:init', icons),
  thumbarPlaying: (playing) => ipcRenderer.invoke('thumbar:playing', playing),
  notify: (title, body) => ipcRenderer.send('notify:show', { title, body }),
  getPathForFile: (file) => { try { return webUtils.getPathForFile(file) || ''; } catch { return ''; } },
  readSessionFiles: (paths) => ipcRenderer.invoke('session:readFiles', paths),
  readFilePrefixes: (paths, maxBytes) => ipcRenderer.invoke('files:readPrefixes', paths, maxBytes),
  soundfontRead: (path) => ipcRenderer.invoke('soundfont:read', path),
  scanDirForAudio: (p, recursive) => ipcRenderer.invoke('files:scanDir', p, recursive),
  libraryPickFolder: () => ipcRenderer.invoke('library:pickFolder'),
  logError: (msg) => ipcRenderer.send('log:error', msg),
  fetchAudioUrl: (url) => ipcRenderer.invoke('url:fetchAudio', url),
  transcodeAudio: (payload) => ipcRenderer.invoke('audio:transcode', payload),
  showInFolder: (p) => ipcRenderer.send('file:showInFolder', p),
  writeFileTags: (payload) => ipcRenderer.invoke('file:writeTags', payload),
  discordConnect: (clientId) => ipcRenderer.send('discord:connect', clientId),
  discordDisconnect: () => ipcRenderer.send('discord:disconnect'),
  discordSetActivity: (activity) => ipcRenderer.send('discord:setActivity', activity),
  discordClearActivity: () => ipcRenderer.send('discord:clearActivity'),
  discordLookupCover: (artist, album, title) => ipcRenderer.invoke('discord:lookupCover', { artist, album, title }),
  metaSearch: (payload) => ipcRenderer.invoke('meta:search', payload),
  metaImage: (url) => ipcRenderer.invoke('meta:image', url),
  onDiscordLog: (cb) => ipcRenderer.on('discord:log', (e, payload) => cb(payload)),
  lyricsFindLocal: (p) => ipcRenderer.invoke('lyrics:findLocal', p),
  lyricsFetch: (meta) => ipcRenderer.invoke('lyrics:fetch', meta),
  lyricsFetchById: (id) => ipcRenderer.invoke('lyrics:fetchById', id),
  lyricsSearch: (query) => ipcRenderer.invoke('lyrics:search', query),
  lyricsSearchNetease: (query) => ipcRenderer.invoke('lyrics:searchNetease', query),
  lyricsFetchNeteaseById: (id) => ipcRenderer.invoke('lyrics:fetchNeteaseById', id),
  lyricsOpenTrackPage: (id) => ipcRenderer.send('lyrics:openTrackPage', id),
  openExternal: (url) => ipcRenderer.send('shell:openExternal', url),
  fetchReleases: () => ipcRenderer.invoke('releases:fetch'),
  icueEnable: () => ipcRenderer.invoke('icue:enable'),
  icueDisable: () => ipcRenderer.invoke('icue:disable'),
  icueFrame: (buf) => ipcRenderer.send('icue:frame', buf),
  lyricsWinToggle: () => ipcRenderer.send('lyrwin:toggle'),
  lyricsWinSet: (open) => ipcRenderer.send('lyrwin:set', open),
  lyricsWinSync: (p) => ipcRenderer.send('lyrwin:sync', p),
  lyricsWinSeek: (t) => ipcRenderer.send('lyrwin:seek', t),
  lyricsWinSetTop: (f) => ipcRenderer.send('lyrwin:setTop', f),
  lyricsWinClose: () => ipcRenderer.send('lyrwin:close'),
  onLyricsWinState: (cb) => ipcRenderer.on('lyrwin:state', (e, open) => cb(open)),
  onLyricsWinSync: (cb) => ipcRenderer.on('lyrwin:sync', (e, p) => cb(p)),
  onLyricsWinHover: (cb) => ipcRenderer.on('lyrwin:hover', (e, v) => cb(!!v)),
  onLyricsWinSeek: (cb) => ipcRenderer.on('lyrwin:seek', (e, t) => cb(t)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (e, percent) => cb(percent)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', () => cb()),
  onUpdateError: (cb) => ipcRenderer.on('update:error', (e, msg) => cb(msg)),
  updateDownload: () => ipcRenderer.send('update:download'),
  updateInstall: () => ipcRenderer.send('update:install'),
  updateOpenReleases: () => ipcRenderer.send('update:openReleases'),
  scrobbleGetAuthUrl: () => ipcRenderer.invoke('scrobble:getAuthUrl'),
  scrobbleCompleteAuth: (token) => ipcRenderer.invoke('scrobble:completeAuth', token),
  scrobbleUpdateNowPlaying: (payload) => ipcRenderer.invoke('scrobble:updateNowPlaying', payload),
  scrobbleTrack: (payload) => ipcRenderer.invoke('scrobble:track', payload),
  scrobbleOpenAuth: (url) => ipcRenderer.send('scrobble:openAuth', url),
  scrobbleGetSimilar: (artist, track) => ipcRenderer.invoke('scrobble:getSimilar', { artist, track }),
});
