const { contextBridge, ipcRenderer, webUtils } = require('electron');
const appVersion = ipcRenderer.sendSync('app:getVersion');

contextBridge.exposeInMainWorld('winControls', {
  appVersion,
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  onMaximizedChange: (cb) => ipcRenderer.on('win:maximized', (e, isMax) => cb(isMax)),
  setAlwaysOnTop: (flag) => ipcRenderer.send('win:setAlwaysOnTop', flag),
  setResizable: (flag) => ipcRenderer.send('win:setResizable', flag),
  setDisplayMode: (mode) => ipcRenderer.send('win:setDisplayMode', mode),
  exportRecording: (buffer, suggestedName, duration, fps, quality) => ipcRenderer.invoke('rec:export', { buffer, suggestedName, duration, fps, quality }),
  onExportProgress: (cb) => ipcRenderer.on('rec:progress', (e, percent) => cb(percent)),
  onMediaPlayPause: (cb) => ipcRenderer.on('media:playpause', () => cb()),
  onMediaNext: (cb) => ipcRenderer.on('media:next', () => cb()),
  onMediaPrev: (cb) => ipcRenderer.on('media:prev', () => cb()),
  onOpenFile: (cb) => ipcRenderer.on('open-file', (e, payload) => cb(payload)),
  setMiniMode: (flag) => ipcRenderer.send('win:setMiniMode', flag),
  shakeWindow: (intensity) => ipcRenderer.send('win:shake', intensity),
  onFadeOut: (cb) => ipcRenderer.on('app:fadeout', () => cb()),
  thumbarInit: (icons) => ipcRenderer.invoke('thumbar:init', icons),
  thumbarPlaying: (playing) => ipcRenderer.invoke('thumbar:playing', playing),
  notify: (title, body) => ipcRenderer.send('notify:show', { title, body }),
  getPathForFile: (file) => { try { return webUtils.getPathForFile(file) || ''; } catch { return ''; } },
  readSessionFiles: (paths) => ipcRenderer.invoke('session:readFiles', paths),
  fetchAudioUrl: (url) => ipcRenderer.invoke('url:fetchAudio', url),
  showInFolder: (p) => ipcRenderer.send('file:showInFolder', p),
  writeFileTags: (payload) => ipcRenderer.invoke('file:writeTags', payload),
  discordConnect: (clientId) => ipcRenderer.send('discord:connect', clientId),
  discordDisconnect: () => ipcRenderer.send('discord:disconnect'),
  discordSetActivity: (activity) => ipcRenderer.send('discord:setActivity', activity),
  discordClearActivity: () => ipcRenderer.send('discord:clearActivity'),
  discordLookupCover: (artist, album) => ipcRenderer.invoke('discord:lookupCover', { artist, album }),
  lyricsFindLocal: (p) => ipcRenderer.invoke('lyrics:findLocal', p),
  lyricsFetch: (meta) => ipcRenderer.invoke('lyrics:fetch', meta),
  lyricsFetchById: (id) => ipcRenderer.invoke('lyrics:fetchById', id),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (e, percent) => cb(percent)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', () => cb()),
  onUpdateError: (cb) => ipcRenderer.on('update:error', (e, msg) => cb(msg)),
  updateDownload: () => ipcRenderer.send('update:download'),
  updateInstall: () => ipcRenderer.send('update:install'),
  updateOpenReleases: () => ipcRenderer.send('update:openReleases'),
});
